<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${subject}</title>
    <style type="text/css">
        /* Notion-style warm monochrome palette */
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f7f6f3; margin: 0; padding: 24px; }
        .container { max-width: 680px; margin: 0 auto; background: #ffffff; border-radius: 8px; padding: 32px 40px; box-shadow: 0 1px 3px rgba(55, 53, 47, 0.08); }
        h1 { color: #1c1a19; font-size: 22px; font-weight: 600; margin: 0 0 24px 0; line-height: 1.3; letter-spacing: -0.01em; }
        .summary { font-size: 15px; line-height: 1.65; color: #37352f; margin-bottom: 32px; padding: 16px 20px; background: #f7f6f3; border-radius: 6px; border: 1px solid #e9e7e4; }
        .items-header { font-size: 12px; color: #9b9a97; text-transform: uppercase; letter-spacing: 0.5px; font-weight: 500; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 1px solid #e9e7e4; }
        .item { padding: 16px 0; border-bottom: 1px solid #e9e7e4; }
        .item:last-child { border-bottom: none; padding-bottom: 0; }
        .item-header { margin-bottom: 8px; }
        .item-position { display: inline-block; background: #2a2725; color: #ffffff; font-size: 11px; font-weight: 500; padding: 3px 8px; border-radius: 4px; margin-right: 10px; vertical-align: middle; }
        .item-title { font-size: 15px; font-weight: 500; color: #1c1a19; text-decoration: none; line-height: 1.4; }
        .item-title:hover { color: #37352f; text-decoration: underline; }
        .item-meta { font-size: 12px; color: #9b9a97; margin-bottom: 6px; margin-left: 36px; }
        .item-score { background: #f1f0ed; padding: 2px 6px; border-radius: 3px; font-weight: 500; color: #6b6a67; }
        .item-summary { font-size: 14px; line-height: 1.55; color: #6b6a67; margin-left: 36px; }
        .footer { margin-top: 32px; padding-top: 20px; border-top: 1px solid #e9e7e4; font-size: 12px; color: #9b9a97; text-align: center; line-height: 1.6; }
        .footer a { color: #37352f; text-decoration: underline; font-weight: 500; }
        .footer a:hover { color: #1c1a19; }
    </style>
</head>
<body>
<div class="container">
    <h1>${subject?html}</h1>

    <div class="summary">
        ${summary?html}
    </div>

    <div class="items-header">Top Stories</div>

    <#list items as item>
    <div class="item">
        <div class="item-header">
            <span class="item-position">${item.position}</span>
            <a href="${item.link?html}" class="item-title" target="_blank">${item.title?html}</a>
        </div>
        <div class="item-meta">
            <span class="item-score">Score: ${item.score}</span>
            <#if item.sourceName??> · ${item.sourceName?html}</#if>
        </div>
        <#if item.summary??>
        <div class="item-summary">${item.summary?html}</div>
        </#if>
    </div>
    </#list>

    <div class="footer">
        Generated by <a href="https://${domain}">Morning Deck</a><br>
        Manage your briefing settings in the app
    </div>
</div>
</body>
</html>
